# Generated by Django 4.1.3 on 2022-11-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=10)),
                ('nombreEntrenador', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('numero', models.IntegerField()),
                ('posicion', models.CharField(max_length=10)),
                ('equipo', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Partidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.IntegerField()),
                ('equipo1', models.CharField(max_length=20)),
                ('equipo2', models.CharField(max_length=20)),
                ('fechaPartido', models.DateField()),
            ],
        ),
    ]
